services:
  postgres:
    image: postgres:16-alpine
    container_name: quiz-postgres
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "5432:5432"
    volumes:
      # Volume kaldırıldı - her restart'ta temiz DB
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - quiz-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: quiz-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: quizuser
      KC_DB_PASSWORD: quizpass
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    command: start-dev
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak-theme/quiz-theme:/opt/keycloak/themes/quiz-theme
    depends_on:
      - postgres
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge